version: '3'

services: 
  webserver:
    build: .
    ports: 
      - 1234:8080
  nginx:
    image: nginx
    volumes: 
      - ./nginx:/usr/share/nginx/html
    ports: 
      - 8080:80
  redis:
    image: redis:alpine
    expose: 
      - 6379